server:
  port: 9090
spring:
  cache:
    ehcache:
      config: classpath:ehcache.xml
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/oracleDB2
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  profiles:
    active: dev