server:
  port: 9090
spring:
  liquibase:
    enabled: true
    change-log: classpath:database/root-changelog.xml
  cache:
    ehcache:
      config: classpath:ehcache.xml
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/oracleDB2
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:8080
      context-path: /admin


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: baity-backend.log
    max-history: 5
    max-size: 10MB