/* INSERT DATA INTO EMPLOYEES TABLE */
INSERT INTO EMPLOYEES 
(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,HIRE_DATE,JOB_TITLE,SALARY,COMMISSION,MANAGER_ID,DEPARTMENT_ID)
VALUES(7369, 'SMITH',  'CLERK','smith.cleark@mail.com','+32004503344',TO_DATE('17-DEC-1980', 'DD-MON-YYYY'),'Enginner', 4000, NULL, 2,5);

/* INSERT DATA INTO EMPLOYEES TABLE */

/* INSERT DATA INTO DEPARTMENTS TABLE */

/* INSERT DATA INTO COUNTRIES TABLE */

/* INSERT DATA INTO JOBS TABLE */

/* INSERT DATA INTO LOCATIONS TABLE */

/* INSERT DATA INTO REGIONS TABLE */